listing_data = [
    {
        "category": "Toys",
        "city": "spanish fork",
        "description": "used great condition Barbie Just Play 28\" Doll - Blonde",
        "displayTime": "2018-09-16T18:48:53Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611061,
        "marketType": "Sale",
        "memberId": 189762,
        "pageviews": "11",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/189762-1537123378-811153.JPG",
        "price": 10,
        "state": "UT",
        "title": "Barbie Just Play  28\" Doll - Blonde"
    },
    {
        "category": "Pets and Livestock",
        "city": "South Jordan",
        "description": "I'm selling my 11 month old Maltese (birthday is oct 14th 2017) I dont have the time anymore to take care of him like he deserves.  He weighs 5 lbs and wont get any bigger.
He's potty trained, kennel trained, and loves other dogs and cats.  He is very sweet and doesn't have a mean bone in his body.  He is up to date on shots, is microchipped, and intact.  I've also consistently brushed his teeth every other day and his teeth are perfectly white and healhty.It breaks my heart selling him, but it is for his best interest.  He is the biggest snuggle buddy and will want to sleep under the covers with you.  He will sleep on your lap as long as you'll let him.  He also prefers being held on his back like a baby.  If you're looking for the perfect lapdog, this is
your puppy.  I paid $1,500 for him so I am pretty firm on the price.  Please text first. 801-502-6020",
        "displayTime": "2018-09-16T18:48:48Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611080,
        "marketType": "Sale",
        "memberId": 1770816,
        "pageviews": "9",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/1770816-1537123290-78147.jpg",
        "price": 800,
        "state": "UT",
        "title": "11 month old male Maltese"
    },
    {
        "category": "Electronics",
        "city": "Providence",
        "description": "Disney infinity collection 1.0 and 2.0 for xbox 360 good condition.",
        "displayTime": "2018-09-16T18:48:47Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611115,
        "marketType": "Sale",
        "memberId": 516294,
        "pageviews": 0,
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/516294-1537123428-963679.jpg",
        "price": 60,
        "state": "UT",
        "title": "Disney Infinity collection"
    },
    {
        "category": "Industrial",
        "city": "West Valley City",
        "description": "NEW DEWALT DC725 18v lithium ion 1/2\u201d Cordless Hammer Drill$120We have two of these for sellIncluded in Kit, Cordless hammer drill, 18 V lithium ion battery, and yellow
battery charger. NEWVoltage: 18V\u2022 Max Power: 450 UWO\u2022 Number of Speed Settings: 3\u2022 Max RPM: 0-500/0-1,250/0-2,000\u2022 Max BPM: 0-8,500/0-21,250/0-34,000\u2022 Clutch Settings: 22\u2022 Chuck Size: 1/2\"\u2022 Chuck Type: Self-tightening\u2022 Tool Weight: 6.25 lbs.Dewalt DC725 Includes:\u2022 Hammerdrill/Drill/Driver\u2022 1-Hour Vehicle Charger\u2022 (2) 18V XRP Batteries\u2022 360\u00b0 Side Handle\u2022 Heavy-Duty Kit Box",
        "displayTime": "2018-09-16T18:48:34Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611113,
        "marketType": "Sale",
        "memberId": 829335,
        "pageviews": "2",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/829335-1537123415-40595.jpg",
        "price": 120,
        "state": "UT",
        "title": "New Dewalt DC725 cordless hammer drill"
    },
    {
        "category": "Recreational Vehicles",
        "city": "payson",
        "description": "Motor is toast I have most of the original parts I was going to put a snowmobile motor on it's all set up for it I don't have time to play Come & Get It",
        "displayTime": "2018-09-16T18:48:18Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611103,
        "marketType": "Sale",
        "memberId": 349131,
        "pageviews": "5",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/349131-1537123360-105549.jpg",
        "price": 300,
        "state": "UT",
        "title": "87 Honda Odyssey"
    },
    {
        "category": "Auto Parts and Accessories",
        "city": "Las Vegas",
        "description": "29 or 31 ford rat rod for sale",
        "displayTime": "2018-09-16T18:48:15Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611111,
        "marketType": "Sale",
        "memberId": 2313306,
        "pageviews": "2",
        "photo": null,
        "price": 2800,
        "state": "NV",
        "title": "Rat Rod  for sale"
    },
    {
        "category": "Electronics",
        "city": "Bountiful",
        "description": "Apple AirPods. In perfect shape comes with Charging Case .",
        "displayTime": "2018-09-16T18:48:06Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611092,
        "marketType": "Sale",
        "memberId": 2720455,
        "pageviews": "4",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/2720455-1537123334-761364.jpeg",
        "price": 90,
        "state": "UT",
        "title": "Apple Airpods"
    },
    {
        "category": "For Trade or Barter",
        "city": "Ogden",
        "description": "2000 Eton Sierra 90 (basically a Polaris) not cheap Chinese junk. Got this for my girlfriends little brother but it doesn't have reverse and we are getting one with reverse for him instead. It runs awesome  just put a brand new battery in it. Really nice condition, barely used and still has the original tires on it in good shape. Headlight and tail lights all work. Has
electric start and backup kick start. Fully automatic just gas and go. I am about 180lbs and it pulls me around with ease. Would be an awesome kids atv. I also have the Clean title in hand. Would only trade for another automatic ATV with reverse. I can put cash on top for the right ATV",
        "displayTime": "2018-09-16T18:47:57Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611107,
        "marketType": "Sale",
        "memberId": 2711542,
        "pageviews": 0,
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/2711542-1537123378-872840.jpg",
        "price": 800,
        "state": "UT",
        "title": "Nice 2000 Eton Sierra 90cc 2stroke"
    },
    {
        "category": "Electronics",
        "city": "Cottonwood Heights",
        "description": "NEW - QFX BT-202 2.1 Bluetooth Speaker SystemNever again settle for tinny laptop speakers. Boost your home entertainment to a new level with QFX's 2.1 channel NFC Bluetooth speaker system. Simply plug the 2.1 channel speaker into the 3.5mm jack of your notebook or music player for rich bass and dynamic surround sound. The 2.1 channel system supports Bluetooth, NFC, USB/SD, and FM playback, all with the convenience of the included remote control.Never again settle for tinny laptop speakers. Boost your home entertainment to a new level with QFX's 2.1 channel NFC Bluetooth speaker system. Simply plug the 2.1 channel speaker into the 3.5mm jack of your notebook or music player for rich bass and dynamic surround sound. The 2.1 channel system supports Bluetooth, NFC, USB/SD, and FM playback, all with the convenience of the included remote control.Features:  FM Radio, Wireless Audio StreamPlacement:  Shelf MountableSound System:  Surround SoundSpeaker Configuration:  2.1RMS Output Power:  20 WWireless Speaker(s):  YesSubwoofer Type:  ActiveNetwork & Communication:  Bluetooth & NFC (Near Field Communication)Compatibility:  PC, MP3 Player, and MP4 PlayerInterfaces/Ports:  USBPackage Contents: -  2.1 Channel NFC Bluetooth Speaker With USB/SD Port -  Remote Control",
        "displayTime": "2018-09-16T18:47:55Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611102,
        "marketType": "Sale",
        "memberId": 889563,
        "pageviews": "4",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/889563-1537123352-657639.jpg",
        "price": 45,
        "state": "UT",
        "title": "NEW - 2.1 Bluetooth Speaker System"
    },
    {
        "category": "Recreational Vehicles",
        "city": "Syracuse",
        "description": "In good condition,  motor rebuild in 2015, comes with an extra set of tires,  hasn't been used much since,  runs but needs the carburetor cleaned since only starts with starting fluid $1300",
        "displayTime": "2018-09-16T18:47:51Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611106,
        "marketType": "Sale",
        "memberId": 1749371,
        "pageviews": "2",
        "photo": null,
        "price": 1300,
        "state": "UT",
        "title": "2000 Polaris Scrambler 400 4x4"
    },
    {
        "category": "Electronics",
        "city": "Murray",
        "description": "No longer have a desktop computer to run this on. Hardly ever used when I did. Text only please",
        "displayTime": "2018-09-16T18:47:44Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611096,
        "marketType": "Sale",
        "memberId": 816783,
        "pageviews": "8",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/816783-1537123348-674103.jpeg",
        "price": 250,
        "state": "UT",
        "title": "Oculus Rift"
    },
    {
        "category": "Furniture",
        "city": "Provo",
        "description": "This is a nice black leather chair with minimum signs of use. Chair is about 4 feet wide by 3 feet deep. Been a great chair with no issues, we just replaced it with a recliner and don't have a spot for it. Located in Provo. 801.362.4219",
        "displayTime": "2018-09-16T18:47:43Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611095,
        "marketType": "Sale",
        "memberId": 776290,
        "pageviews": "8",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/776290-1537123341-73941.JPG",
        "price": 20,
        "state": "UT",
        "title": "Nice black leather sofa seat chair"
    },
    {
        "category": "Cycling",
        "city": "Park City Or Heber City",
        "description": "Like new used once maxxis minion dhf 27.5x2.50 tire,  tubeless ready ,exo protection ......for questions text only please, cash only, thanks for watching ",
        "displayTime": "2018-09-16T18:47:41Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611105,
        "marketType": "Sale",
        "memberId": 2741414,
        "pageviews": "4",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/2741414-1537123382-486906.jpg",
        "price": 35,
        "state": "UT",
        "title": "MAXXIS MINION DHF 27.5x2.50"
    },
    {
        "category": "Auto Parts and Accessories",
        "city": "Eagle Mountain",
        "description": "BF Goodrich 245 75 17 all terrain tries. Not sure of the miles, but in good condition. They\u2019ll go 20,000-30,000 miles more. The wheels are not included at this price. Text is best.",
        "displayTime": "2018-09-16T18:47:38Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611065,
        "marketType": "Sale",
        "memberId": 351383,
        "pageviews": "6",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/351383-1537123250-147199.jpeg",
        "price": 250,
        "state": "UT",
        "title": "245 75 17 f150 wheels"
    },
    {
        "category": "Furniture",
        "city": "Riverton",
        "description": "They still have lots of life left. They are basically new. We used them to stage a house we sold.They've been in storage for awhile so they would just need a bit of cleaning.Price is for both stools - not each. Its slightly negotiable - but if you shoot me a low ball offer I most likely will ignore. Cash Only.Pick-Up in Riverton.",
        "displayTime": "2018-09-16T18:47:37Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611104,
        "marketType": "Sale",
        "memberId": 2613560,
        "pageviews": 0,
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/2613560-1537123360-198940.jpg",
        "price": 125,
        "state": "UT",
        "title": "Denim Studded Stools"
    },
    {
        "category": "Recreational Vehicles",
        "city": "SLC",
        "description": "ROGUE PLATINUM PACKAGE GEL COAT SIDE WALLS ALUMIFOIL INSULATION 30 GALLON FUEL STATION AND GEN PREP GLASS SHOWER ENCLOSURE HAPPIJAC BED LIFT-TOP BED WITH BOTTOM BED COUCH COMBO POWER TONGUE JACK RAISED PANEL WOOD REFER FRONT 15K AIR CONDITIONER RVIA SEAL",
        "displayTime": "2018-09-16T18:47:35Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53246246,
        "marketType": "Sale",
        "memberId": 474557,
        "pageviews": "45",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/474557-1535244242-833645.jpg",
        "price": 50852.75,
        "state": "UT",
        "title": "2018 Forest River VENGEANCE 25V"
    },
    {
        "category": "Furniture",
        "city": "Layton",
        "description": "29x19\" print on canvas. Check out the other art listed--take the whole lot for just $55!",
        "displayTime": "2018-09-16T18:47:31Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611101,
        "marketType": "Sale",
        "memberId": 3374476,
        "pageviews": 0,
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/3374476-1537123352-664975.jpg",
        "price": 10,
        "state": "UT",
        "title": "Guitar Print on Canvas"
    },
    {
        "category": "Recreational Vehicles",
        "city": "Marion",
        "description": "For sale well equipped Ranger, includes complete cab system,winch,cab heater, windshield wiper/washer, 2 inch lift,just had service done.  All service done at Wellers Recreation. ",
        "displayTime": "2018-09-16T18:47:29Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611100,
        "marketType": "Sale",
        "memberId": 29770,
        "pageviews": 0,
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/29770-1537123351-818866.jpg",
        "price": 19000,
        "state": "UT",
        "title": "2016 Polaris Ranger XP Crew 900"
    },
    {
        "category": "Furniture",
        "city": "South Jordan",
        "description": "Does have a bit of wear on the corners ",
        "displayTime": "2018-09-16T18:47:27Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611099,
        "marketType": "Sale",
        "memberId": 2930136,
        "pageviews": "2",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/2930136-1537123353-907909.jpg",
        "price": 15,
        "state": "UT",
        "title": "Small Decorative Trunk With Latch "
    },
    {
        "category": "Furniture",
        "city": "Draper",
        "description": "Beautiful oak china display / storage hutch with glass shelves. 2 piece bundle \u2013 top and bottom with lighted top. Excellent for displaying collectibles and heirlooms as
well as china.  Glass door and glass shelves provide great visibility while lower cabinet piece provides loads of storage for safekeeping and organization. Local sales only \u2013 you pick up. Call
or text Brian (801) 953-9363.",
        "displayTime": "2018-09-16T18:47:26Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611094,
        "marketType": "Sale",
        "memberId": 116410,
        "pageviews": "7",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/116410-1537123337-555211.jpg",
        "price": 100,
        "state": "UT",
        "title": "Oak China Display Storage Hutch"
    },
    {
        "category": "Home and Garden",
        "city": "Tooele",
        "description": "Anchor Hocking - Prescut Clear - 2 Part Relish DishLike NewExquisite details and timeless vintage style.",
        "displayTime": "2018-09-16T18:47:15Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611064,
        "marketType": "Sale",
        "memberId": 3363416,
        "pageviews": "9",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/3363416-1537123306-647910.JPG",
        "price": 10,
        "state": "UT",
        "title": "Anchor Hocking - Prescut Clear - Relish Dish"
    },
    {
        "category": "Recreational Vehicles",
        "city": "Salt Lake City",
        "description": "Fully custom \u201873 scrambler with tons of upgrades. This bike had a full engine rebuild a few years ago and had 10,400 miles at the time. Since the rebuild, she\u2019s only added about 1,000 more miles. Mikuni racing carbs, K&N pod filters, Cafe Racer Dreams headlight imported from Spain, DCC mini speedometer, Tommaselli Daytona grips, black low rise bars, custom upholstered seat, new wiring and heat shrink. I haven\u2019t used this motorcycle in 2 years and figured it should go to a new home. The bike tipped in the trailer while I was moving it to SLC and pinched a wire so one of the rear blinkers needs re-wired. Currently needs a tune up because it\u2019s been sitting for 2 years and will only idle for a minute but I have no doubts it will run like a champ with a quick tune up. Text preferred $2,700 OBONO TRADES",
        "displayTime": "2018-09-16T18:47:08Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611093,
        "marketType": "Sale",
        "memberId": 3022804,
        "pageviews": "2",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/3022804-1537123331-487122.jpg",
        "price": 2700,
        "state": "UT",
        "title": "1973 Honda CL350 Cafe Racer"
    },
    {
        "category": "Pets and Livestock",
        "city": "Sandy",
        "description": "Great dogs, very well behaved!  One is 6 and the other is 7 years old.  Must go together.  Fully potty trained.  Very good with kids.  Comes with crates, beds, food, all the
necessitys!",
        "displayTime": "2018-09-16T18:46:54Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611090,
        "marketType": "Sale",
        "memberId": 2411129,
        "pageviews": "6",
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/2411129-1537123315-388921.jpg",
        "price": 250,
        "state": "UT",
        "title": "Two puggles"
    },
    {
        "category": "Appliances",
        "city": "Salt Lake City",
        "description": "Works great! Needs a plug but otherwise no issues. ",
        "displayTime": "2018-09-16T18:46:50Z",
        "favoriteStatus": "unfavorited",
        "favorited": 0,
        "id": 53611089,
        "marketType": "Sale",
        "memberId": 913122,
        "pageviews": 0,
        "photo": "//img.ksl.com/mx/mplace-classifieds.ksl.com/913122-1537123311-690519.jpg",
        "price": 40,
        "state": "UT",
        "title": "Kenmore electric range/oven"
    }
]

